name: Submit Json to Metadata Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Submit Json
      run: |
        python submit.py
      env:
        ENDPOINT: ${{ secrets.ENDPOINT }}
